analyze_health_report:
  description: >
    Analyze the provided blood test report and identify key health indicators.
    Summarize the findings in a clear and concise manner.
    Ensure to capture the patient's ...


    PDF file: {path_to_pdf}
  expected_output: >
    A structured summary of key health indicators from the blood test report (in json).
  agent: >
    analyzer

find_relevant_articles:
  description: >
    Using the analysis, search the internet for relevant health articles that fit the person's needs.
    Summarize the key points from the top articles and add a link to the article.
    Give a relevancy score based on the relevancy of an article (1 being the least relevant and 10 being the most) according to the person's needs.
  expected_output: >
    A structured summary of relevant health articles along with their links and relevancy score (in json).
  agent: >
    researcher
    
filter_articles:
  description: >
    Search the internet and give a credebility score (1 being the least credible and 10 being the most) to every article based on answers to (and not limited to) the following questions:
    - When was the article published and is it valid in 2024?
    - How many citations are there for the article (more the citations, more trustworthy)?
    - Who the author is? - a little background would be nice
    - Is the conference in which the paper was published reputable (again, more the reputation, more trustworthiness)?
    - Are the references in the article valid?
    And more.
    The above questions would not give relevant answers if you search them on iternet, so come up with better search queries.
    Multiply the final credibility score of an article to its relevancy score to get the priority of the article.
  expected_output: >
    Return a json that was recieved from the researcher along with a credibility score and priority assigned to each article. 
  agent: >
    filter

health_recommendations:
  description: >
    Based on the research findings, make health recommendations tailored to the individual's needs.
    Ensure the recommendations are practical and evidence-based. 
    Use the priority score (1 being the least priority and 100 being the most) to determine the relevancy and credibility of an article.
  expected_output: >

  agent: >
    advisor
